/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ActivateAccountRouteImport } from './routes/activate-account'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedEmployeeIndexRouteImport } from './routes/_protected/employee/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedEmployeeCreateRouteImport } from './routes/_protected/employee/create'
import { Route as ProtectedEmployeeEmployeeIdIndexRouteImport } from './routes/_protected/employee/$employeeId/index'
import { Route as ProtectedAdminUsersIndexRouteImport } from './routes/_protected/admin/users/index'
import { Route as ProtectedEmployeeEmployeeIdEditRouteImport } from './routes/_protected/employee/$employeeId/edit'
import { Route as ProtectedAdminUsersUserIdRouteImport } from './routes/_protected/admin/users/$userId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateAccountRoute = ActivateAccountRouteImport.update({
  id: '/activate-account',
  path: '/activate-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEmployeeIndexRoute = ProtectedEmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedEmployeeCreateRoute = ProtectedEmployeeCreateRouteImport.update({
  id: '/employee/create',
  path: '/employee/create',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEmployeeEmployeeIdIndexRoute =
  ProtectedEmployeeEmployeeIdIndexRouteImport.update({
    id: '/employee/$employeeId/',
    path: '/employee/$employeeId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminUsersIndexRoute =
  ProtectedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedEmployeeEmployeeIdEditRoute =
  ProtectedEmployeeEmployeeIdEditRouteImport.update({
    id: '/employee/$employeeId/edit',
    path: '/employee/$employeeId/edit',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminUsersUserIdRoute =
  ProtectedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate-account': typeof ActivateAccountRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/employee/create': typeof ProtectedEmployeeCreateRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/employee/': typeof ProtectedEmployeeIndexRoute
  '/admin/users/$userId': typeof ProtectedAdminUsersUserIdRoute
  '/employee/$employeeId/edit': typeof ProtectedEmployeeEmployeeIdEditRoute
  '/admin/users/': typeof ProtectedAdminUsersIndexRoute
  '/employee/$employeeId/': typeof ProtectedEmployeeEmployeeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate-account': typeof ActivateAccountRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/employee/create': typeof ProtectedEmployeeCreateRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/employee': typeof ProtectedEmployeeIndexRoute
  '/admin/users/$userId': typeof ProtectedAdminUsersUserIdRoute
  '/employee/$employeeId/edit': typeof ProtectedEmployeeEmployeeIdEditRoute
  '/admin/users': typeof ProtectedAdminUsersIndexRoute
  '/employee/$employeeId': typeof ProtectedEmployeeEmployeeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/activate-account': typeof ActivateAccountRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/employee/create': typeof ProtectedEmployeeCreateRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/employee/': typeof ProtectedEmployeeIndexRoute
  '/_protected/admin/users/$userId': typeof ProtectedAdminUsersUserIdRoute
  '/_protected/employee/$employeeId/edit': typeof ProtectedEmployeeEmployeeIdEditRoute
  '/_protected/admin/users/': typeof ProtectedAdminUsersIndexRoute
  '/_protected/employee/$employeeId/': typeof ProtectedEmployeeEmployeeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate-account'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/employee/create'
    | '/admin/'
    | '/employee/'
    | '/admin/users/$userId'
    | '/employee/$employeeId/edit'
    | '/admin/users/'
    | '/employee/$employeeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate-account'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/profile'
    | '/employee/create'
    | '/admin'
    | '/employee'
    | '/admin/users/$userId'
    | '/employee/$employeeId/edit'
    | '/admin/users'
    | '/employee/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/activate-account'
    | '/reset-password'
    | '/verify-email'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/_protected/profile'
    | '/_protected/employee/create'
    | '/_protected/admin/'
    | '/_protected/employee/'
    | '/_protected/admin/users/$userId'
    | '/_protected/employee/$employeeId/edit'
    | '/_protected/admin/users/'
    | '/_protected/employee/$employeeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ActivateAccountRoute: typeof ActivateAccountRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-account': {
      id: '/activate-account'
      path: '/activate-account'
      fullPath: '/activate-account'
      preLoaderRoute: typeof ActivateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/employee/': {
      id: '/_protected/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof ProtectedEmployeeIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/employee/create': {
      id: '/_protected/employee/create'
      path: '/employee/create'
      fullPath: '/employee/create'
      preLoaderRoute: typeof ProtectedEmployeeCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/employee/$employeeId/': {
      id: '/_protected/employee/$employeeId/'
      path: '/employee/$employeeId'
      fullPath: '/employee/$employeeId/'
      preLoaderRoute: typeof ProtectedEmployeeEmployeeIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/users/': {
      id: '/_protected/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof ProtectedAdminUsersIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/employee/$employeeId/edit': {
      id: '/_protected/employee/$employeeId/edit'
      path: '/employee/$employeeId/edit'
      fullPath: '/employee/$employeeId/edit'
      preLoaderRoute: typeof ProtectedEmployeeEmployeeIdEditRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/users/$userId': {
      id: '/_protected/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof ProtectedAdminUsersUserIdRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedAdminUsersUserIdRoute: typeof ProtectedAdminUsersUserIdRoute
  ProtectedAdminUsersIndexRoute: typeof ProtectedAdminUsersIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedAdminUsersUserIdRoute: ProtectedAdminUsersUserIdRoute,
  ProtectedAdminUsersIndexRoute: ProtectedAdminUsersIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedEmployeeCreateRoute: typeof ProtectedEmployeeCreateRoute
  ProtectedEmployeeIndexRoute: typeof ProtectedEmployeeIndexRoute
  ProtectedEmployeeEmployeeIdEditRoute: typeof ProtectedEmployeeEmployeeIdEditRoute
  ProtectedEmployeeEmployeeIdIndexRoute: typeof ProtectedEmployeeEmployeeIdIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedEmployeeCreateRoute: ProtectedEmployeeCreateRoute,
  ProtectedEmployeeIndexRoute: ProtectedEmployeeIndexRoute,
  ProtectedEmployeeEmployeeIdEditRoute: ProtectedEmployeeEmployeeIdEditRoute,
  ProtectedEmployeeEmployeeIdIndexRoute: ProtectedEmployeeEmployeeIdIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ActivateAccountRoute: ActivateAccountRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
