services:
  db-hris:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=hris_admin
      - POSTGRES_PASSWORD=hris_password
      - POSTGRES_DB=hris
    ports:
      - "5432:5432"
    volumes:
      - db-hris:/var/lib/postgresql/data
    # network_mode: 'host'
  redis-hris:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-hris:/data
      - ./redis-conf:/usr/local/etc/redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    # network_mode: "host"
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    # network_mode: 'host'
  mailpit:
    image: axllent/mailpit:v1.27
    ports:
      - "1025:1025"
      - "8025:8025"
    # network_mode: 'host'

volumes:
  db-hris:
    driver: local
  redis-hris:
    driver: local